AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This is a url redirection tool for your domain (similar to bit.ly)
Resources:
  redirectLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: redirect.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          dynamodb_table: !Ref redirectDynamoDB
      Events:
        Api:
          Type: Api
          Properties:
            Path: /redirect/{proxy+}
            Method: ANY
  redirectDynamoDB:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: id
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
